# Generated by Django 3.2.12 on 2022-05-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
